#!/bin/bash
# Launch the 4-GPU generative-critic smoke test on Tillicum through Mason.
set -euo pipefail

BEAKER_IMAGE="${1:?Pass the Beaker image as the first argument}"
EXP_NAME="genac_smoke_tillicum_$(date +%Y%m%d_%H%M%S)"

uv run python mason.py \
    --cluster ai2/tillicum \
    --image "$BEAKER_IMAGE" \
    --pure_docker_mode \
    --workspace ai2/olmo-instruct \
    --priority urgent \
    --preemptible \
    --num_nodes 1 \
    --gpus 4 \
    --max_retries 0 \
    --no_auto_dataset_cache \
    --env VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 \
    --env VLLM_ALLOW_INSECURE_SERIALIZATION=1 \
    --env NCCL_CUMEM_ENABLE=0 \
    --env PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
    -- source configs/beaker_configs/ray_node_setup.sh \&\& python open_instruct/grpo_fast_genvalue.py \
    --exp_name "$EXP_NAME" \
    --dataset_mixer_list ai2-adapt-dev/rlvr_gsm8k_zs 64 \
    --dataset_mixer_list_splits train \
    --dataset_mixer_eval_list ai2-adapt-dev/rlvr_gsm8k_zs 16 \
    --dataset_mixer_eval_list_splits train \
    --max_prompt_token_length 512 \
    --response_length 256 \
    --pack_length 1024 \
    --per_device_train_batch_size 1 \
    --num_unique_prompts_rollout 4 \
    --num_samples_per_prompt_rollout 2 \
    --model_name_or_path Qwen/Qwen3-0.6B \
    --add_bos \
    --stop_strings "</answer>" \
    --apply_r1_style_format_reward \
    --apply_verifiable_reward true \
    --ground_truths_key ground_truth \
    --chat_template_name r1_simple_chat_postpend_think \
    --temperature 0.7 \
    --beta 0.0 \
    --learning_rate 3e-7 \
    --total_episodes 32 \
    --deepspeed_stage 2 \
    --num_epochs 1 \
    --num_learners_per_node 1 \
    --vllm_num_engines 1 \
    --vllm_tensor_parallel_size 1 \
    --vllm_sync_backend gloo \
    --vllm_gpu_memory_utilization 0.4 \
    --vllm_enforce_eager \
    --inflight_updates True \
    --async_steps 2 \
    --seed 3 \
    --local_eval_every 3 \
    --save_freq 100 \
    --gradient_checkpointing \
    --with_tracking False \
    --push_to_hub False \
    --output_dir /tmp/genac_smoke_output \
    --use_value_model \
    --value_learning_rate 5e-6 \
    --gae_lambda 0.95 \
    --gamma 1.0 \
    --value_loss_coef 0.0 \
    --vf_clip_range 0.2 \
    --use_generative_value_model \
    --gen_value_model_name_or_path Qwen/Qwen3-0.6B \
    --gen_value_vllm_num_engines 1 \
    --gen_value_vllm_tensor_parallel_size 1 \
    --gen_value_segmentation fixed \
    --gen_value_chunk_size 64 \
    --gen_value_max_segments 4 \
    --gen_value_score_min 0 \
    --gen_value_score_max 10 \
    --gen_value_max_new_tokens 128 \
    --gen_value_conditioning none \
    --gen_value_learning_rate 1e-6 \
    --gen_value_reinforce_coef 0.1 \
    --gen_value_sync_freq 1
